### ISSUE TITLE
no output on P1.6

### ISSUE THREAD

**Issue by altineller** [fmilburn3/WS2812#1]
Hello,

I tried running this with energia, msp430g2553. It did not light up the leds, so I checked the mosi pin (and other pins as well) and it does not produce the usual output for the ws2812 leds, i mean there is no output or voltage change on the scope screen.

What could have gone wrong?

**Comment by fmilburn3** [comment]
The output is on pin P1.7 (MOSI) - see comments in code.  Not sure what is wrong if it does not work for you.  Make sure you don’t power the WS2812s with 5V as the MSP430s are not 5V tolerant.

**Comment by altineller** [comment]
I looked up the wrong pin map from energia site, (which they removed the 2553) so this was my mistake.
I also got it to work with TivaC with the following settings:

#define SPIDIV     SPI_CLOCK_DIV2      
#define SPILONG    0b11100000        
#define SPISHORT   0b10000000        

Also, it seems that while transmitting from MOSI, it also pulls down the CS of the SPI port. (Naturally)

Is there a way to avoid that behaivor?

Best Regards,

**Comment by fmilburn3** [comment]
There was a post on 43oh about using this same method with the Tiva C.  There are also some posts that use assembly to do the timing which might work the other problem if I remember correctly.  You could do a search on 43oh.
